TBWEB/Controllers/AgencyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TBWeb.Models;

namespace TBWeb.Controllers
{
    public class AgencyController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /Agency/
        public async Task<ActionResult> Index()
        {
            var agencies = db.Agencies.Include(a => a.City).Include(a => a.Country).Include(a => a.State);
            return View(await agencies.ToListAsync());
        }

        // GET: /Agency/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agency agency = await db.Agencies.FindAsync(id);
            if (agency == null)
            {
                return HttpNotFound();
            }
            ViewBag.CityId = agency.CityId;
            ViewBag.CountryId = agency.CountryId;
            ViewBag.StateId = agency.StateId;

            ViewBag.CustomerProfiles = db.CustomerProfiles;
            ViewBag.Destinations = db.Destinations;
            ViewBag.PaymentMethods = db.PaymentMethods;
            ViewBag.Products = db.Products;

            return View(agency);
        }

        // GET: /Agency/Create
        public ActionResult Create()
        {

            ViewBag.CustomerProfiles = db.CustomerProfiles;
            ViewBag.Destinations = db.Destinations;
            ViewBag.PaymentMethods = db.PaymentMethods;
            ViewBag.Products = db.Products;
            return View();
        }

        // POST: /Agency/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "AgencyId,Name,RegistryNumber,CUIT,Adress,PostalCode,CityId,StateId,CountryId,AgencyPhone,AgencyPhone2,Extension,Extension2,WebPage,Password,ConfirmPassword,EMail,ConfirmEmail,PriceRangeFrom,PriceRangeTo")] Agency agency, string[] CustomerProfiles, string[] Destinations, string[] PaymentMethods, string[] Products)
        {
            agency.Country = db.Countries.Find(agency.CountryId);
            agency.State = db.States.Find(agency.StateId);
            agency.City = db.Cities.Find(agency.CityId );


            if (CustomerProfiles != null)
            {
             foreach (string c in CustomerProfiles)
            {
                agency.CustomerProfiles.Add(db.CustomerProfiles.Find(int.Parse(c)));
            }
           }
            if (Destinations != null)
            {
             foreach (string c in Destinations)
            {
                agency.Destinations.Add(db.Destinations.Find(int.Parse(c)));
            }
            }
            if (PaymentMethods != null)
            {
            foreach (string c in PaymentMethods)
            {
                agency.PaymentMethods.Add(db.PaymentMethods.Find(int.Parse(c)));
            }
            }
            if (Products != null)
            {
                foreach (string c in Products)
                {
                    agency.Products.Add(db.Products.Find(int.Parse(c)));
                }
            }

                db.Agencies.Add(agency);
                await db.SaveChangesAsync();

            ViewBag.CityId = agency.CityId;
            ViewBag.CountryId = agency.CountryId;
            ViewBag.StateId = agency.StateId;

            ViewBag.CustomerProfiles = db.CustomerProfiles;
            ViewBag.Destinations = db.Destinations;
            ViewBag.PaymentMethods = db.PaymentMethods;
            ViewBag.Products = db.Products;

//            return RedirectToAction("Index");

            return View(agency);
        }

        // GET: /Agency/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agency agency = await db.Agencies.FindAsync(id);
            if (agency == null)
            {
                return HttpNotFound();
            }
            
            ViewBag.CityId = agency.CityId;
            ViewBag.CountryId = agency.CountryId;
            ViewBag.StateId = agency.StateId;

            ViewBag.CustomerProfiles = db.CustomerProfiles;
            ViewBag.Destinations = db.Destinations;
            ViewBag.PaymentMethods = db.PaymentMethods;
            ViewBag.Products = db.Products;

            return View(agency);
        }

        // POST: /Agency/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "AgencyId,Name,Ranking,RegistryNumber,CUIT,Adress,PostalCode,CityId,StateId,CountryId,AgencyPhone,AgencyPhone2,Extension,Extension2,WebPage,Password,ConfirmPassword,EMail,ConfirmEmail,PriceRangeFrom,PriceRangeTo,MemberCategoryId")] Agency agency, string[] CustomerProfiles, string[] Destinations, string[] PaymentMethods, string[] Products)
        {
            agency.Country = db.Countries.Find(agency.CountryId);
            agency.State = db.States.Find(agency.StateId);
            agency.City = db.Cities.Find(agency.CityId);

            if (CustomerProfiles != null)
            {
                foreach (string c in CustomerProfiles)
                {
                    agency.CustomerProfiles.Add(db.CustomerProfiles.Find(int.Parse(c)));
                }
            }
            if (Destinations != null)
            {
            foreach (string c in Destinations)
            {
                agency.Destinations.Add(db.Destinations.Find(int.Parse(c)));
            }
            }
            if (PaymentMethods != null)
            {
            foreach (string c in PaymentMethods)
            {
                agency.PaymentMethods.Add(db.PaymentMethods.Find(int.Parse(c)));
            }
            }
            if (Products != null)
            {
                foreach (string c in Products)
                {
                    agency.Products.Add(db.Products.Find(int.Parse(c)));
                }
            }
            if (ModelState.IsValid)
            {
                db.Entry(agency).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CityId = agency.CityId;
            ViewBag.CountryId = agency.CountryId;
            ViewBag.StateId = agency.StateId;

            ViewBag.CustomerProfiles = db.CustomerProfiles;
            ViewBag.Destinations = db.Destinations;
            ViewBag.PaymentMethods = db.PaymentMethods;
            ViewBag.Products = db.Products;
            return View(agency);
        }

        // GET: /Agency/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agency agency = await db.Agencies.FindAsync(id);
            if (agency == null)
            {
                return HttpNotFound();
            }
            return View(agency);
        }

        // POST: /Agency/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Agency agency = await db.Agencies.FindAsync(id);
            db.Agencies.Remove(agency);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TBWEB/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TBWeb.Models;

namespace TBWeb.Controllers
{
    public class NewsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /News/
        public async Task<ActionResult> Index()
        {
            return View(await db.News.ToListAsync());
        }

        // GET: /News/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = await db.News.FindAsync(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // GET: /News/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /News/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include="NewsId,NewsTitle,NewsBody,NewsURL,NewsImage,NewsPostDate")] News news)
        {
            if (ModelState.IsValid)
            {
                db.News.Add(news);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(news);
        }

        // GET: /News/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = await db.News.FindAsync(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: /News/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include="NewsId,NewsTitle,NewsBody,NewsURL,NewsImage,NewsPostDate")] News news)
        {
            if (ModelState.IsValid)
            {
                db.Entry(news).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(news);
        }

        // GET: /News/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = await db.News.FindAsync(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: /News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            News news = await db.News.FindAsync(id);
            db.News.Remove(news);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TBWEB/Controllers/TripsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using System.Web.Mvc;
using TBWeb.Models;

namespace TBWeb.Controllers
{
    public class TripsController : ApiController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET api/Trips
        public IQueryable<Trip> GetTrips()
        {
            return db.Trips.OrderBy(m => m.TripId);
        }


        // GET api/CustomerBids/query

        public IQueryable<Trip> GetTrips(String query)
        {
            IQueryable<Trip> trips = null;
            if (query != null && query != "")
                trips = db.Trips.Where(x => x.Destination.Contains(query)).OrderBy(m => m.TripId);
            else
                trips = db.Trips.OrderBy(m => m.TripId);
            return trips;
        }



        // GET api/Trips/5
        [ResponseType(typeof(Trip))]
        public async Task<IHttpActionResult> GetTrip(int id)
        {
            Trip trip = await db.Trips.FindAsync(id);
            if (trip == null)
            {
                return NotFound();
            }

            return Ok(trip);
        }

        // PUT api/Trips/5
        public async Task<IHttpActionResult> PutTrip(int id, Trip trip)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != trip.TripId)
            {
                return BadRequest();
            }

            db.Entry(trip).State = EntityState.Modified;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TripExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST api/Trips
        [ResponseType(typeof(Trip))]
        public async Task<IHttpActionResult> PostTrip(Trip trip)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Trips.Add(trip);
            await db.SaveChangesAsync();

            return CreatedAtRoute("DefaultApi", new { id = trip.TripId }, trip);
        }

        // DELETE api/Trips/5
        [ResponseType(typeof(Trip))]
        public async Task<IHttpActionResult> DeleteTrip(int id)
        {
            Trip trip = await db.Trips.FindAsync(id);
            if (trip == null)
            {
                return NotFound();
            }

            db.Trips.Remove(trip);
            await db.SaveChangesAsync();

            return Ok(trip);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool TripExists(int id)
        {
            return db.Trips.Count(e => e.TripId == id) > 0;
        }

      
    }
}

TBWEB/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TBWEB/Views/Home/Admin.cshtml
@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Admin</h2>


<div class="col-xs-1">
    @Html.ActionLink("Customer Profiles","index","CustomerProfiles")

</div>
<div class="col-xs-1">
    @Html.ActionLink("Usuarios", "index", "Account")

</div>
<div class="col-xs-1">
    @Html.ActionLink("Agencias", "index", "Agency")

</div>
<div class="col-xs-1">
    @Html.ActionLink("Usuarios de Agencias", "index", "AgencyUser")

</div>
<div class="col-xs-1">
    @Html.ActionLink("Categoria de Miembros", "index", "MembersCategories")

</div>
<div class="col-xs-1">
    @Html.ActionLink("Noticias", "index", "News")

</div>
<div class="col-xs-1">
    @Html.ActionLink("Formas de Pago", "index", "PaymentMethod")

</div>
<div class="col-xs-1">
    @Html.ActionLink("Productos", "index", "Products")

</div>
<div class="col-xs-1">
    @Html.ActionLink("Continentes", "index", "Continents")

</div>
<div class="col-xs-1">
    @Html.ActionLink("Regiones", "index", "Regions")

</div>
<div class="col-xs-1">
    @Html.ActionLink("Paises", "index", "Countries")

</div>
<div class="col-xs-1">
    @Html.ActionLink("Estados", "index", "States")

</div>
<div class="col-xs-1">
    @Html.ActionLink("Ciudades", "index", "Cities")

</div>

TBWEB/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TBWEB/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Inicio";
}

<div class="container visible-xs">
    <div class="col-md-5">
        <form>
            <div class="row input-append">
                <input class="search-query col-md-5" placeholder="Donde queres viajar?" type="search" data-bind="value: query, valueUpdate: 'keyup'" autocomplete="off">
            </div>
            <div class="row input-append">
                <button type="submit" class=" btn btn-success btn-large">Arma tu viaje</button>
                <button type="submit" class=" btn btn-primary btn-large">Ver cotizaciones</button>
                <div>
                    <a class="btn" href="@Url.Action("Index", "Groups")" id="A1">
                        <span class="font-icon-group"></span> All Groups
                    </a>
                </div>
            </div>
        </form>

    </div>
    </div>
    <div class="container hidden-xs">
    <!-- Carousel
       ================================================== -->
    <div id="myCarousel" class="carousel slide ">
        <div class="carousel-inner">



            <div class="item active">
                <img src="~/img/768x1366/Cocktail-Beach-Drink-768x1366.jpg" alt="">
                <div class="container">
                    <div class="carousel-caption">
                        <div class="controls-row">

                        </div>



                    </div>
                </div>
            </div>
            <div class="item">
                <img src="~/img/768x1366/Four-Seasons-Bora-Bora-Resort-768x1366.jpg" alt="">
                <div class="container">
                    <div class="carousel-caption">
                        <div class="controls-row">

                        </div>



                    </div>
                </div>
            </div>
            <div class="item">
                <img src="~/img/768x1366/perito-moreno-glacier-argentina-768x1366.jpg" alt="">
                <div class="container">
                    <div class="carousel-caption">
                        <div class="controls-row">

                        </div>



                    </div>
                </div>

            </div>
        </div>
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>

        <div class="row">
            <div class=" col-md-12 carousel-title">
                <form>
                    <div class="input-append col-md-12">
                        <h1>Ahorra tiempo y dinero!</h1>
                        <p class="lead">Deja que las agencias compitan por tu viaje</p>
                    </div>
                </form>
            </div>
        </div>


                <div class="offset7 col-md-5 carouselsearch">
                    <form>
                        <div class="row input-append">
                        <input class="search-query col-md-5" placeholder="Donde queres viajar?" type="search" data-bind="value: query, valueUpdate: 'keyup'" autocomplete="off">
                        </div>
                        <div class="row input-append">
                            <button type="submit" class=" btn btn-success btn-large">Arma tu viaje</button>
                            <button type="submit" class=" btn btn-primary btn-large">Ver cotizaciones</button>
                                 </div>
                    </form>

            </div>


    <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>

</div>
        </div>



<div id="Results" class="row">
    <div class="col-lg-3 col-md-3 pull-left">
        <div class="col-md-3">
            <ul class="nav nav-pills nav-stacked " id="left-sidebar" style="display: none">
                <li class="list-group-item active">Mis Viajes</li>
                <li class="list-group-item">@Html.ActionLink("Crear nuevo viaje!", "Create", "Trips")</li>
            </ul>
        </div>
        
        @Html.Partial("../News/_partialNewsList");

    </div>
    <div class="col-lg-9 col-md-9 col-xs-12 pull-right" >
    @Html.Partial("../Trips/_partialMyTrips");

</div>



</div>


<div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row">
        <div class="col-md-3">
            <h3>Informacion</h3>
            <p>Completa la informacion de tu viaje</p>
            <img class="img-circle" src="~/img/informacion.png" />
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="glyphicon glyphicon-chevron-right"></span>
        </div>
        <div class="col-md-3">
            <h3>Cotizaciones</h3>
            <p>Recibi las cotizaciones de las agencias</p>
            <img class="img-circle" src="~/img/cotizaciones.png" />
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="glyphicon glyphicon-chevron-right"></span>
        </div>
        <div class="col-md-3">
            <h3>Seleccion</h3>
            <p>Elegi la cotizacion que mas te convenga</p>
            <img class="img-circle" src="~/img/seleccion.png" />
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="glyphicon glyphicon-chevron-right"></span>
        </div>
        <div class="col-md-3">
            <h3>Viaja</h3>
            <p>Empeza a disfrutar tu viaje</p>
            <img class="img-circle" src="~/img/viaja.png" />
        </div>
    </div><!-- /.row -->
    <!-- START THE FEATURETTES -->
    @*<hr class="featurette-divider">

        <div class="featurette">
            <img class="featurette-image pull-right" src="../assets/img/examples/browser-icon-chrome.png">
            <h2 class="featurette-heading">Queres viajar?<span class="muted">Recibi cotizaciones de las agencias.</span></h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>

        <hr class="featurette-divider">

        <div class="featurette">
            <img class="featurette-image pull-left" src="../assets/img/examples/browser-icon-firefox.png">
            <h2 class="featurette-heading">Oh yeah, it's that good. <span class="muted">See for yourself.</span></h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>

        <hr class="featurette-divider">

        <div class="featurette">
            <img class="featurette-image pull-right" src="../assets/img/examples/browser-icon-safari.png">
            <h2 class="featurette-heading">And lastly, this one. <span class="muted">Checkmate.</span></h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>

        <hr class="featurette-divider">*@

    <!-- /END THE FEATURETTES -->
    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "brand" })
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                        @Html.Partial("_LoginPartial")
                    </div>
                </div>
            </div>
        </div>*@

    <!-- FOOTER -->





</div>

TBWEB/Views/Home/_AjaxCustomerList.cshtml
@using MvcPaging
@model IPagedList<TBWeb.Models.Customer>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Name
            </th>
            <th>
                Email
            </th>
            <th>
                City
            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.CustomerId
                </td>
                <td>
                    @item.Name
                </td>
                <td>
                    @item.Mail
                </td>
                <td>
                    @item.City
                </td>
            </tr>
        }

    </tbody>

</table>
<div class="pager1">
    @Html.Raw(Ajax.Pager(
            new Options
            {
                PageSize = Model.PageSize,
                TotalItemCount = Model.TotalItemCount,
                CurrentPage = Model.PageNumber,
                ItemTexts = new ItemTexts() { Next = "Next", Previous = "Previous", Page = "P" },
                ItemIcon = new ItemIcon() { First = "icon-backward", Previous = "icon-chevron-left", Next = "icon-chevron-right", Last = "icon-forward" },
                TooltipTitles = new TooltipTitles() { Next = "Next page", Previous = "Previous page", Page = "Page {0}." },
                Size = Size.normal,
                Alignment = Alignment.centered,
                IsShowControls = true,
                IsShowFirstLast = true,
                CssClass = ""
            },
            new AjaxOptions
            {
                UpdateTargetId = "grid-list",
                OnBegin = "beginPaging",
                OnSuccess = "successPaging",
                OnFailure = "failurePaging"
            }, new { controller = "Home", action = "Index", Customer_name = ViewData["Customer_name"] }))
    <div class="well">
        Showing <span class="badge badge-success">@Model.ItemStart</span> to <span class="badge badge-success">@Model.ItemEnd</span>
        of <span class="badge badge-info">@Model.TotalItemCount</span> entries</div>
</div>
@*<script src="../../Scripts/bootstrap.min.js" type="text/javascript"></script>*@